# 一个通用的单数据库配置。

[alembic]
# 迁移脚本的路径。
# 这通常是一个以 POSIX 格式（例如使用正斜杠）给出的路径，
# 相对于变量 %(here)s（指代此 ini 文件所在的目录）。
script_location = %(here)s/alembic

# 用于生成迁移文件名的模板；默认值为 %%(rev)s_%%(slug)s
# 如果你希望在文件名前加上日期和时间，请取消下面一行的注释。
# 所有可用的标记（tokens）请参考：
# https://alembic.sqlalchemy.org/en/latest/tutorial.html#editing-the-ini-file
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s
# 或者组织成基于日期的子目录（需要设置 recursive_version_locations = true）
# file_template = %%(year)d/%%(month).2d/%%(day).2d_%%(hour).2d%%(minute).2d_%%(second).2d_%%(rev)s_%%(slug)s

# sys.path 路径，如果存在，将预先添加到 sys.path 中。
# 默认为当前工作目录。如果包含多个路径，
# 路径分隔符由下方的 "path_separator" 定义。
prepend_sys_path = .


# 在迁移文件内部以及文件名中渲染日期时使用的时区。
# 如果指定，则需要 tzdata 库，可以通过安装 `alembic[tz]` 来获取。
# 字符串值将传递给 ZoneInfo()
# 留空则使用本地时间（localtime）
# timezone =

# 应用于 "slug" 字段（文件名中的描述部分）的最大字符长度
# truncate_slug_length = 40

# 设置为 'true'，则无论是否使用 autogenerate，
# 都会在执行 'revision' 命令期间运行环境（env.py）
# revision_environment = false

# 设置为 'true'，允许在 versions/ 目录中将没有 .py 源文件的
# .pyc 和 .pyo 文件检测为版本。
# sourceless = false

# 版本文件位置说明；默认为 <script_location>/versions。
# 当使用多个版本目录时，初始版本必须通过 --version-path 指定。
# 此处使用的路径分隔符应为下方 "path_separator" 指定的字符。
# version_locations = %(here)s/bar:%(here)s/bat:%(here)s/alembic/versions

# path_separator；指定用于拆分文件路径列表（包括 version_locations 
# 和 prepend_sys_path）的字符。
# 新生成的 alembic.ini 默认渲染为 "os"，即使用 os.pathsep 根据操作系统自动拆分。
#
# 注意：为了支持旧版本的 alembic.ini 文件，如果 path_separator 不存在，
# 则不会生效。如果完全省略此选项，回退逻辑如下：
#
# 1. 解析 version_locations 选项时，回退到使用旧的 "version_path_separator" 键，
#    如果该键也缺失，则回退到使用空格和/或逗号拆分的旧行为。
# 2. 解析 prepend_sys_path 选项时，回退到使用空格、逗号或冒号拆分的旧行为。
#
# path_separator 的有效值包括：
#
# path_separator = :
# path_separator = ;
# path_separator = space
# path_separator = newline
#
# 使用 os.pathsep。新项目的默认配置。
path_separator = os

# 设置为 'true'，以递归搜索每个 "version_locations" 目录中的源文件
# Alembic 1.10 版本新增
# recursive_version_locations = false

# 写入修订（revision）脚本时使用的输出编码。
# output_encoding = utf-8

# 数据库 URL。这仅由用户维护的 env.py 脚本使用。
# 其他配置数据库 URL 的方式可以在 env.py 文件中自定义。
sqlalchemy.url = driver://user:pass@localhost/dbname


[post_write_hooks]
# post_write_hooks 定义了在新建修订脚本上运行的脚本或 Python 函数。
# 详情和示例请参阅文档。

# 使用 "black" 进行格式化 - 使用 console_scripts 运行器，针对 "black" 入口点
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REVISION_SCRIPT_FILENAME

# 使用 "ruff" 进行 lint 检查并尝试修复 - 使用 module 运行器，针对 "ruff" 模块
hooks = ruff
ruff.type = module
ruff.module = ruff
ruff.options = check --fix REVISION_SCRIPT_FILENAME

# 或者，使用 exec 运行器执行在环境变量 PATH 中找到的二进制文件
# hooks = ruff
# ruff.type = exec
# ruff.executable = ruff
# ruff.options = check --fix REVISION_SCRIPT_FILENAME

# 日志配置。这同样仅由用户维护的 env.py 脚本使用。
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S